### ISSUE TITLE
Paths for Steam installation

### ISSUE THREAD

**Issue by filipham** [ThyWoof/UMM-MAC-PathFinderKingMaker#1]
For steam version of the game, paths are different: 

Install your mods here: 
/Users/<YOURUSER>/Library/Application Support/Steam/steamapps/common/Pathfinder Kingmaker/Mods

Install the extracted ZIP from ThyWoof here: 
/Users/<YOURUSER>/Library/Application Support/Steam/steamapps/common/Pathfinder Kingmaker/Kingmaker.app/Contents/Resources/Data/Managed

**Comment by ThyWoof** [comment]
Updated instructions. Thanks!
