### ISSUE TITLE
A Big Thanks

### ISSUE THREAD

**Issue by amittos** [ThyWoof/UMM-MAC-PathFinderKingMaker#4]
I found this on [Reddit](https://www.reddit.com/r/Pathfinder_Kingmaker/comments/e5lptr/macos_catalina_and_unity_mod_manager/), but since the comments are locked, I would just like to say a big thanks for this. If I could buy you a cup of coffee I would.

**Comment by ThyWoof** [comment]
Lol. Glad I could help. Will do the same for Pathfinder: WoTR once it gets released.
